version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:13.9
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simplebank
    volumes:
      - ./docker-seed/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "simple_bank"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1s0s
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
